// <auto-generated />
namespace Oleg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OutLay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OutLay));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071807042_OutLay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
