// <auto-generated />
namespace Oleg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DB2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB2));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071054390_DB2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
