// <auto-generated />
namespace Oleg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DB1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB1));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071019390_DB1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
