// <auto-generated />
namespace Oleg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LeaderShip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeaderShip));
        
        string IMigrationMetadata.Id
        {
            get { return "201603092223442_LeaderShip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
