// <auto-generated />
namespace Oleg.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Vacansions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vacansions));
        
        string IMigrationMetadata.Id
        {
            get { return "201603072058067_Vacansions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
